CONTRIBUTING.md

Closes https://github.com/Kagamihime/VIlain/issues/1
Don't hesitate to tell me if there is anything that should be corrected or explained better ;)

CONTRIBUTING.md: Add contributing guidelines

---

.coafile
.gitignore
README.md
coala.sh

Closes https://github.com/Kagamihime/VIlain/issues/3
Everything is explained in the commits' messages ;)

Integrate coala

---

CONTRIBUTING.md

This adds explanations about how to use the script `coala.sh`
in order to easily run checks on the project.
Closes https://github.com/Kagamihime/VIlain/issues/15

CONTRIBUTING.md: Add explanations for coala

---

Makefile
include/buffer.h
include/cursor.h
include/io_text.h
include/settings.h
include/ui.h
src/buffer.c
src/cursor.c
src/io_text.c
src/main.c
src/settings.c
src/ui.c

The skeleton contains all the files that will be needed for the project.
The modules contains all the prototypes of the functions that will be needed.
The Makefile allows to compile all the files using "$make all"
Closes https://github.com/Kagamihime/VIlain/issues/7

Add project's skeleton

---

Makefile
include/buffer.h
include/cursor.h
include/settings.h
include/ui.h

This applies patches suggested by coala.
Closes https://github.com/Kagamihime/VIlain/issues/25

Fix coala warnings on the Makefile and the header files

---

.travis.yml
Makefile
include/buffer.h
include/settings.h
include/ui.h

Integrate Travis and do some last corrections for it to work.
Closes https://github.com/Kagamihime/VIlain/issues/12

Integrate Travis CI

---

include/buffer.h
src/buffer.c

This implements almost (except three) all the functions of the buffer and makes some adjustments to its API.
Closes https://github.com/Kagamihime/VIlain/issues/9

First implementation of the buffer

---

include/cursor.h
src/cursor.c

Closes https://github.com/Kagamihime/VIlain/issues/11

Implementation of the cursor

---

include/cursor.h
src/cursor.c

I had forgotten to write a constructor to initialize an empty cursor so I added it.

Add the function new_curs()

---

include/buffer.h
src/buffer.c

This complete the buffer implementation and modify the API:
- Some functions as been reordered
- New functions has been introduced
See the commits for more informations.
Closes https://github.com/Kagamihime/VIlain/issues/35

Almost complete the buffer implementation and do API adjustments

---

src/buffer.c

This adds conditionals so that erroneous shifting are not
done on empty lines or buffer.
Fixes https://github.com/Kagamihime/VIlain/issues/44

buffer.c: Add conditionals

---

src/buffer.c

Closes https://github.com/Kagamihime/VIlain/issues/47

buffer.c: Implement `join_lines`

---

.coafile
include/buffer.h
src/buffer.c
tests/Makefile
tests/check_vilain.c

These are tests for the buffer. There are still more tests to write before it is completed but this brings also important fixes for the buffer.
Closes https://github.com/Kagamihime/VIlain/issues/36

Start to write tests for the buffer

---

.travis.yml

Closes https://github.com/Kagamihime/VIlain/issues/55

.travis.yml: Add the tests in the build process

---

.gitignore

Closes https://github.com/Kagamihime/VIlain/issues/57

.gitignore: Add the test's binary

---

tests/Makefile

Fixes https://github.com/Kagamihime/VIlain/issues/61

Makefile: Add libncurses

---

include/ui.h
src/main.c
src/ui.c

There are still a lot of things to do on this module but I think it's good if you can have access to the functions I've done so far.
Some areas are in comments because they do not work for the moment.
This is a work in progress.

First implementation of the ui

---

src/buffer.c
tests/check_vilain.c

Closes https://github.com/Kagamihime/VIlain/issues/54

Complete the tests for the buffer

---

include/settings.h
src/settings.c

This fixes the problem when a file did not exist
Closes https://github.com/Kagamihime/VIlain/issues/75

src/settings.c: Adjust the function load again

---

src/buffer.c
tests/check_vilain.c

Closes https://github.com/Kagamihime/VIlain/issues/37

Allow the buffer to grow when needed

---

src/io_text.c

Closes https://github.com/Kagamihime/VIlain/issues/83

src/io_text.c: Remove FILE_MAX_LENGTH and LINE_MAX_LENGTH

---

src/buffer.c

Closes https://github.com/Kagamihime/VIlain/issues/90

Cleanup the code of the buffer

---

include/settings.h
src/settings.c

I created a new function `char* to_string(int code` and I changed the type `char*` to `int` for all the shortcuts

Change the module settings.c in order to work with the ui implementation

---

etc/ui.cfg

Closes https://github.com/Kagamihime/VIlain/issues/100

ui.cfg: Write the default configuration

---

src/io_text.c

Closes https://github.com/Kagamihime/VIlain/issues/94

Refactor some of the code in io_text.c

---

README.md

Closes https://github.com/Kagamihime/VIlain/issues/118

README.md: Write informations about the project

---

tests/check_vilain.c

I haven't split the tests with cases since tests are very basics and only depends on if a path of a file is a good one or not.

tests.check_vilain.c: Write tests for 'io_text'

---

Makefile

I need this to push my function to save automatically the buffer please

Makefile: Add -lpthread option
